certificateAuthorities:
  ca.orderer.test.com:
    caName: ca.orderer.test.com
    registrar:
      enrollId: admin
      enrollSecret: adminpw
    tlsCaCerts:
      client:
        cert:
          path: ''
          pem: ''
        key:
          path: ''
          pem: ''
      path: /etc/hyperledger/fabric-ca-server/ca-cert.pem
      pem: ca-cert.pem
    url: http://localhost:7054
  ca.org0.test.com:
    caName: ca.org0.test.com
    registrar:
      enrollId: admin
      enrollSecret: adminpw
    tlsCaCerts:
      client:
        cert:
          path: ''
          pem: ''
        key:
          path: ''
          pem: ''
      path: /etc/hyperledger/fabric-ca-server/ca-cert.pem
      pem: ca-cert.pem
    url: http://localhost:7054
  ca.org1.test.com:
    caName: ca.org1.test.com
    registrar:
      enrollId: admin
      enrollSecret: adminpw
    tlsCaCerts:
      client:
        cert:
          path: ''
          pem: ''
        key:
          path: ''
          pem: ''
      path: /etc/hyperledger/fabric-ca-server/ca-cert.pem
      pem: ca-cert.pem
    url: http://localhost:7054
  ca.org2.test.com:
    caName: ca.org2.test.com
    registrar:
      enrollId: admin
      enrollSecret: adminpw
    tlsCaCerts:
      client:
        cert:
          path: ''
          pem: ''
        key:
          path: ''
          pem: ''
      path: /etc/hyperledger/fabric-ca-server/ca-cert.pem
      pem: ca-cert.pem
    url: http://localhost:7054
channels:
  channel-1:
    eventService:
      blockHeightLagThreshold: 5
      minBlockHeightResolverMode: ResolveByThreshold
      peerMonitor: Enabled
      peerMonitorPeriod: 5s
      reconnectBlockHeightLagThreshold: 10
      resolverStrategy: PreferOrg
    orderers:
    - orderer0.orderer.test.com
    - orderer1.orderer.test.com
    - orderer2.orderer.test.com
    peers:
      peer0.org0.test.com:
        chaincodeQuery: true
        endorsingPeer: true
        eventSource: true
        ledgerQuery: true
      peer0.org1.test.com:
        chaincodeQuery: true
        endorsingPeer: true
        eventSource: true
        ledgerQuery: true
      peer0.org2.test.com:
        chaincodeQuery: true
        endorsingPeer: true
        eventSource: true
        ledgerQuery: true
    polices:
      queryChannelConfig:
        maxTargets: 1
        minResponses: 1
        retryOpts:
          attempts: 5
          backoffFactor: '2.0'
          initialBackoff: 500ms
          maxBackoff: 5s
    selection:
      Balancer: RoundRobin
      BlockHeightLagThreshold: 5
      SortingStrategy: BlockHeightPriority
client:
  BCCSP:
    security:
      default:
        hashAlgorithm: SHA2
        label: label
        level: 256
        library: ''
        pin: pin
        provider: SW
        softVerify: true
      enable: true
  credentialStore:
    cryptoStore:
      path: /tmp/msp
    path: /tmp/state-store
  cryptoconfig:
    path: /root/go/src/fabric-go-sdk/fixtures/crypto-config
  discovery:
    timeout:
      connection: 15s
      response: 15s
  eventService:
    timeout:
      connection: 15s
      registrationResponse: 15s
    type: deliver
  global:
    cache:
      channelConfig: 30m
      channelMembership: 30s
      connectionIdle: 30s
      discovery: 10s
      eventServiceIdle: 2m
      selection: 10m
    timeout:
      execute: 180s
      query: 180s
      resmgmt: 180s
  logging:
    level: info
  orderer:
    timeout:
      connection: 15s
      response: 15s
  organization: orderer.test.com
  peer:
    timeout:
      connection: 10s
      discovery:
        greylistExpiry: 10s
      response: 180s
  tlsCerts:
    cert:
      path: ''
    key:
      path: ''
    systemCertPool: true
description: Faber
entityMatchers:
  certificateAuthority:
  - ignoreEndpoint: false
    mappedHost: ca.orderer.test.com
    pattern: (\w*)ca.orderer.test.com(\w*)
    sslTargetOverrideUrlSubstitutionExp: ''
    urlSubstitutionExp: http://localhost:7054
  - ignoreEndpoint: false
    mappedHost: ca.org0.test.com
    pattern: (\w*)ca.org0.test.com(\w*)
    sslTargetOverrideUrlSubstitutionExp: ''
    urlSubstitutionExp: http://localhost:7054
  - ignoreEndpoint: false
    mappedHost: ca.org1.test.com
    pattern: (\w*)ca.org1.test.com(\w*)
    sslTargetOverrideUrlSubstitutionExp: ''
    urlSubstitutionExp: http://localhost:7054
  - ignoreEndpoint: false
    mappedHost: ca.org2.test.com
    pattern: (\w*)ca.org2.test.com(\w*)
    sslTargetOverrideUrlSubstitutionExp: ''
    urlSubstitutionExp: http://localhost:7054
  channel:
  - ignoreEndpoint: false
    mappedHost: channel-1
    pattern: channel-1$
    sslTargetOverrideUrlSubstitutionExp: ''
    urlSubstitutionExp: ''
  orderer:
  - ignoreEndpoint: false
    mappedHost: orderer0.orderer.test.com
    pattern: (\w*)orderer0.orderer.test.com(\w*)
    sslTargetOverrideUrlSubstitutionExp: orderer0.orderer.test.com
    urlSubstitutionExp: localhost:7050
  - ignoreEndpoint: false
    mappedHost: orderer1.orderer.test.com
    pattern: (\w*)orderer1.orderer.test.com(\w*)
    sslTargetOverrideUrlSubstitutionExp: orderer1.orderer.test.com
    urlSubstitutionExp: localhost:7050
  - ignoreEndpoint: false
    mappedHost: orderer2.orderer.test.com
    pattern: (\w*)orderer2.orderer.test.com(\w*)
    sslTargetOverrideUrlSubstitutionExp: orderer2.orderer.test.com
    urlSubstitutionExp: localhost:7050
  peers:
  - ignoreEndpoint: false
    mappedHost: peer0.org0.test.com
    pattern: (\w*)peer0.org0.test.com(\w*)
    sslTargetOverrideUrlSubstitutionExp: localhost:7053
    urlSubstitutionExp: localhost:7051
  - ignoreEndpoint: false
    mappedHost: peer0.org1.test.com
    pattern: (\w*)peer0.org1.test.com(\w*)
    sslTargetOverrideUrlSubstitutionExp: localhost:7053
    urlSubstitutionExp: localhost:7051
  - ignoreEndpoint: false
    mappedHost: peer0.org2.test.com
    pattern: (\w*)peer0.org2.test.com(\w*)
    sslTargetOverrideUrlSubstitutionExp: localhost:7053
    urlSubstitutionExp: localhost:7051
name: faber
orderers:
  orderer0.orderer.test.com:
    grpcOptions:
      allow-insecure: false
      fail-fast: true
      keep-alive-permit: false
      keep-alive-time: 5s
      keep-alive-timeout: 6s
      ssl-target-name-override: orderer0.orderer.test.com
    tlsCaCerts:
      path: /var/hyperledger/orderer/tls/tlscacerts/tls.pem
    url: localhost:7050
  orderer1.orderer.test.com:
    grpcOptions:
      allow-insecure: false
      fail-fast: true
      keep-alive-permit: false
      keep-alive-time: 5s
      keep-alive-timeout: 6s
      ssl-target-name-override: orderer1.orderer.test.com
    tlsCaCerts:
      path: /var/hyperledger/orderer/tls/tlscacerts/tls.pem
    url: localhost:7050
  orderer2.orderer.test.com:
    grpcOptions:
      allow-insecure: false
      fail-fast: true
      keep-alive-permit: false
      keep-alive-time: 5s
      keep-alive-timeout: 6s
      ssl-target-name-override: orderer2.orderer.test.com
    tlsCaCerts:
      path: /var/hyperledger/orderer/tls/tlscacerts/tls.pem
    url: localhost:7050
organizations:
  orderer.test.com:
    mspId: ordererMSP
    peers:
    - ca.orderer.test.com
    - orderer0.orderer.test.com
    - orderer1.orderer.test.com
    - orderer2.orderer.test.com
  org0.test.com:
    mspId: org0MSP
    peers:
    - ca.org0.test.com
    - peer0.org0.test.com
  org1.test.com:
    mspId: org1MSP
    peers:
    - ca.org1.test.com
    - peer0.org1.test.com
  org2.test.com:
    mspId: org2MSP
    peers:
    - ca.org2.test.com
    - peer0.org2.test.com
peers:
  peer0.org0.test.com:
    eventUrl: localhost:7053
    grpcOptions:
      allow-insecure: false
      fail-fast: true
      keep-alive-permit: false
      keep-alive-time: 5s
      keep-alive-timeout: 6s
      ssl-target-name-override: peer0.org0.test.com
    tlsCaCerts:
      path: /etc/hyperledger/fabric/tls/tlscacerts/tls.pem
    url: localhost:7051
  peer0.org1.test.com:
    eventUrl: localhost:7053
    grpcOptions:
      allow-insecure: false
      fail-fast: true
      keep-alive-permit: false
      keep-alive-time: 5s
      keep-alive-timeout: 6s
      ssl-target-name-override: peer0.org1.test.com
    tlsCaCerts:
      path: /etc/hyperledger/fabric/tls/tlscacerts/tls.pem
    url: localhost:7051
  peer0.org2.test.com:
    eventUrl: localhost:7053
    grpcOptions:
      allow-insecure: false
      fail-fast: true
      keep-alive-permit: false
      keep-alive-time: 5s
      keep-alive-timeout: 6s
      ssl-target-name-override: peer0.org2.test.com
    tlsCaCerts:
      path: /etc/hyperledger/fabric/tls/tlscacerts/tls.pem
    url: localhost:7051
version: 1.0.0
