networks:
  net:
    external:
      name: FabricDraw
services:
  ca.org2.test.com:
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    container_name: ca.org2.test.com
    environment:
    - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
    - FABRIC_CA_SERVER_CA_NAME=ca-org2
    - FABRIC_CA_SERVER_TLS_ENABLED=true
    - FABRIC_CA_SERVER_PORT=12054
    - FABRIC_CA_SERVER_CSR_HOSTS=localhost, ca.org2.test.com
    image: hyperledger/fabric-ca:1.4.7
    networks:
    - net
    ports:
    - 12054:12054
    volumes:
    - /root/opt/crypto-config/peerOrganizations/org2.test.com/ca:/etc/hyperledger/fabric-ca-server
version: '2'
