networks:
  net:
    external:
      name: FabricDraw
services:
  ca.orderer.test.com:
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    container_name: ca.orderer.test.com
    environment:
    - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
    - FABRIC_CA_SERVER_CA_NAME=ca-orderer
    - FABRIC_CA_SERVER_TLS_ENABLED=true
    - FABRIC_CA_SERVER_PORT=7054
    - FABRIC_CA_SERVER_CSR_HOSTS=localhost, ca.orderer.test.com
    image: hyperledger/fabric-ca:1.4.7
    networks:
    - net
    ports:
    - 7054:7054
    volumes:
    - /root/opt/crypto-config/ordererOrganizations/orderer.test.com/ca:/etc/hyperledger/fabric-ca-server
version: '2'
