OrdererOrgs:
- Name: Orderer
  Domain: orderer.test.com
  EnableNodeOUs: true
  Specs:
  - Hostname: orderer
    SANS:
    - localhost
PeerOrgs:
- Name: org0
  Domain: org0.test.com
  EnableNodeOUs: true
  Template:
    Count: 2
    SANS:
    - localhost
    - localhost
  Users:
    Count: 1
- Name: org1
  Domain: org1.test.com
  EnableNodeOUs: true
  Template:
    Count: 2
    SANS:
    - localhost
    - localhost
  Users:
    Count: 1
- Name: org2
  Domain: org2.test.com
  EnableNodeOUs: true
  Template:
    Count: 2
    SANS:
    - localhost
    - localhost
  Users:
    Count: 1
