version: '2'

networks:
  net:
    external:
      name: root_test

services:

  ca.org1.test.com:
    image: hyperledger/fabric-ca:1.4.7
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org1
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
      - FABRIC_CA_SERVER_CSR_HOSTS=localhost, ca.org1.test.com
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - $CRYPTO_BASE/organizations/fabric-ca/org1:/etc/hyperledger/fabric-ca-server
    container_name: ca.org1.test.com
    networks:
      - net
